project_id = "ldlrhoyklfvcctmuewqf"

[functions.enrich-product]
verify_jwt = false

[functions.scrape-assets]
verify_jwt = false

[functions.enrich-batch]
verify_jwt = false

[functions.download-asset]
verify_jwt = false

[functions.razorpay]
verify_jwt = false
